# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UO Sports Analysis
email: uosportsanalysis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  UOSA is a student group at the University of Oregon interested in the quantitative exploration of
  sports data, both in-game and out.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uosportsanalysis.github.io" # the base hostname & protocol for your site
twitter:
  username:  jackwchristy

# Collections
collections:
  members:
    output: true

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
